### ISSUE TITLE
the explorer Account page  field mistake

### ISSUE THREAD

**Issue by cyberskycat** [CasperLabs/clarity#119]
the second field should be "**Account Hex**", not "**Account Hash**"

### js sdk result

![image](https://user-images.githubusercontent.com/47585428/113168239-1241d580-9277-11eb-91c7-1b401a781a6d.png)

![image](https://user-images.githubusercontent.com/47585428/113167979-d0b12a80-9276-11eb-83c3-675d7a8fe879.png)

**Comment by George-cl** [comment]
Hi @cyberskycat, development is no longer taking place in this repo. Feel free to raise issues with Clarity [here](https://github.com/make-software/casper-clarity).
Thanks!
