### ISSUE TITLE
Showing error as "Error During Transform" in Stitch

### ISSUE THREAD

**Issue by HarshJoshi1997** [CasperLabs/clarity#74]
Hello Team,

I'm Stitch tool and have connected with the COVID-19 datasource using API token granted by the GitHub. I was able to successfully integrate the data and was also able to set-up the desired destination but when I tried to extract the data it showed the error as "**Error During Transform**". The problem is I was able to see the data loaded into the warehouse which is SnowFlake in my case. 

So the question is, if the datasoucre is suceesfully integrated and destination is also succuessfully set-up as well as the data is also loaded into the "Data Warehouse (Snowflake)" then why I'm getting the error as "**Error During Transform**".

I'm also attaching below the screenshots of the errors that I'm getting for the reference.

![image](https://user-images.githubusercontent.com/76017798/102154212-ed2f7f80-3e9e-11eb-91a4-1de00b92f10a.png)

![image](https://user-images.githubusercontent.com/76017798/102154265-03d5d680-3e9f-11eb-8e18-80eb575c5f19.png)

Hoping the team can help me in this issue.

Thanks and Warm Regards,
Harsh

**Comment by George-cl** [comment]
I think you might be in the wrong place so I'm going to close this, cheers.
